In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import professional snooker matches data form 1982 to 2025
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/Data/matches.csv')
matches.head()

,player1,player2,score1,score2,best_of,tournament_id,date,year
0,Colin Roscoe,Jackie Rea,9,6,17,753,NaN,1982
1,Tommy Murphy,Clive Everton,9,4,17,753,NaN,1982
2,Vic Harris,Marcus Owen,9,4,17,753,NaN,1982
3,Bob Harris,Graham Cripsey,9,6,17,753,NaN,1982
4,Geoff Foulds,Matt Gibson,9,3,17,753,NaN,1982

In [3]:
#Predict the match result, expected frame win rate and matches win rate of the 1080th tournament
from elo_v4 import elo_rating
tournaments = list(matches.tournament_id.unique())
past_tournaments = tournaments[:1080]
current = tournaments[1080]
past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)

matches_past = matches[past_index]
matches_future = matches[matches['tournament_id'] == current]

elo = elo_rating()
elo.update_stats(matches = matches_past)

prediction , frames_win_rates, match_win_rates = elo.predict(matches_future[['player1', 'player2', 'best_of']])


matches_future.loc[:, 'prediction'] = prediction
matches_future.loc[:, 'frames_win_rates'] = frames_win_rates
matches_future.loc[:, 'match_win_rates'] = match_win_rates

/Users/tliu/Desktop/Erdos Project/Elo Rating/elo_v4/elo_v4.py:112: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.stats_by_years.fillna(0, inplace = True)
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_2164/1401998010.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future.loc[:, 'prediction'] = prediction
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_2164/1401998010.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future.loc[:, 'frames_win_rates'] = frames_win_rates
/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_2164/1401998010.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_future.loc[:, 'match_win_rates'] = match_win_rates

In [4]:
matches_future[['player1', 'player2', 'best_of', 'prediction', 'frames_win_rates', 'match_win_rates']]

,player1,player2,best_of,prediction,frames_win_rates,match_win_rates
115002,Wang Yuchen,Brian Cini,19,False,0.563407,0.713067
115003,Dean Young,Michal Szubarczyk,19,False,0.575054,0.747538
115004,Gao Yang,Liam Pullen,19,False,0.550453,0.672492
115005,Zhao Xintong,Cheung Ka Wai,19,False,0.677542,0.947558
115006,Jimmy White,Anton Kazakov,19,False,0.632394,0.883148
...,...,...,...,...,...,...
115139,Judd Trump,Luca Brecel,25,False,0.610639,0.871101
115140,Ronnie O'Sullivan,Si Jiahui,25,False,0.577495,0.784511
115141,Zhao Xintong,Ronnie O'Sullivan,33,True,0.481259,0.414091
115142,Mark Williams,Judd Trump,33,True,0.412170,0.152740
115143,Zhao Xintong,Mark Williams,35,False,0.504375,0.520790