In this notebook, we use the elo rating system to generate statistics of players from past matches.  
Columns: ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo'
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage']

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import professional snooker matches data form 1982 to 2025
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/1_Match_Data/matches.csv')
matches.head()

,player1,player2,score1,score2,best_of,tournament_id,date,year
0,Colin Roscoe,Jackie Rea,9,6,17,753,NaN,1982
1,Tommy Murphy,Clive Everton,9,4,17,753,NaN,1982
2,Vic Harris,Marcus Owen,9,4,17,753,NaN,1982
3,Bob Harris,Graham Cripsey,9,6,17,753,NaN,1982
4,Geoff Foulds,Matt Gibson,9,3,17,753,NaN,1982

In [ ]:
from elo_v4 import elo_rating

#Store all the tournaments in a list
tournaments = list(matches.tournament_id.unique())
#nth means nth tournament among 1085 tournaments
nth = range(985,1035)


data = pd.DataFrame(columns = ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage', 'tournament_id'])



for n in nth:
  past_tournaments = tournaments[:n]
  print(f'Generating data for the {n}th tournament')
  current = tournaments[n]
  past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
  
  matches_past = matches[past_index]
  matches_future = matches[matches['tournament_id'] == current]
  matches_future_X = matches_future[['player1', 'player2', 'best_of']]

  #Update statistics of players
  elo = elo_rating()
  elo.update_stats(matches = matches_past)
  stats = elo.stats
  sby = elo.stats_by_years
  player_stats = elo.generate_stats(matches_future_X)

  results = np.zeros(len(matches_future))
  win_perc = matches_future['score1'] / (matches_future['score1'] + matches_future['score2'])

  
  new_data = player_stats
  new_data['score1'] = matches_future['score1'].values
  new_data['score2'] = matches_future['score2'].values
  new_data['match_result'] = results
  new_data['win_percentage'] = win_perc.values
  new_data['tournament_id'] = tournaments[n]
  

  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 985th tournament

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_7474/405913041.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 986th tournament
Generating data for the 987th tournament
Generating data for the 988th tournament
Generating data for the 989th tournament
Generating data for the 990th tournament
Generating data for the 991th tournament
Generating data for the 992th tournament
Generating data for the 993th tournament
Generating data for the 994th tournament
Generating data for the 995th tournament
Generating data for the 996th tournament
Generating data for the 997th tournament
Generating data for the 998th tournament
Generating data for the 999th tournament
Generating data for the 1000th tournament

In [ ]:
data.sample(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
1088,Stuart Bingham,Gary Wilson,5,1427,1394,0.538606,0.520613,1474,930,10188,...,371,9,4,641,334,3,0,0.0,1.000000,5964
1950,Subrat Das,Hassan Gull,7,1000,1000,0.500000,0.500000,0,0,0,...,0,0,0,0,0,4,3,0.0,0.571429,6142
1119,Mark Selby,Xiao Guodong,5,1547,1426,0.638626,0.575054,1519,1039,10874,...,531,12,6,744,393,3,2,0.0,0.600000,5964
2391,Wu Yize,Ross Muir,4,1322,1202,0.790118,0.574443,101,48,723,...,264,60,25,395,185,3,1,0.0,0.750000,6194
2798,Liam Graham,Mink Nutcharut,7,985,949,0.549086,0.522485,49,14,271,...,62,53,12,246,70,4,1,0.0,0.800000,6219

In [ ]:
data

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Cao Yupeng,Jiang Jun,9,1411,1044,0.918016,0.714532,341,179,2302,...,242,32,17,32,17,5,0,0.0,1.000000,5808
1,Zhou Yuelong,Siripaporn Nuanthakhamjan,9,1384,965,0.943119,0.740295,459,272,2879,...,430,23,4,23,4,5,2,0.0,0.714286,5808
2,Wu Yize,Allan Taylor,9,1342,1237,0.656987,0.565251,78,37,552,...,215,101,49,336,147,5,3,0.0,0.625000,5808
3,Ben Woollaston,Oliver Brown,9,1412,1146,0.845318,0.660383,803,454,5053,...,282,91,35,235,97,5,2,0.0,0.714286,5808
4,Mark Williams,Andres Petrov,9,1611,1045,0.982235,0.804553,1751,1151,12775,...,649,79,25,167,61,5,2,0.0,0.714286,5808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5053,Connor Benzey,John Astley,7,1083,1245,0.290008,0.400112,38,19,195,...,52,11,7,241,108,4,2,0.0,0.666667,6803
5054,Fergal Quinn (II),Dean Young,7,1049,1110,0.417243,0.461949,43,20,229,...,62,72,32,400,172,4,1,0.0,0.800000,6803
5055,David Grace,Jack Borwick,7,1244,976,0.818679,0.661503,504,232,3294,...,199,8,4,67,26,4,0,0.0,1.000000,6803
5056,Ian Burns,Andrew Pagett,7,1278,1094,0.734971,0.613014,520,252,3294,...,216,37,13,390,160,4,1,0.0,0.800000,6803
5057,Connor Benzey,Rodion Judin,7,1083,961,0.661777,0.575664,38,19,195,...,52,6,2,49,19,4,2,0.0,0.666667,6803

In [ ]:
data.to_csv('match_data_985_1035_tourns.csv', index=False)