In the match data generated in data_generation.ipynb, player1 is always the winner. For the purpose of future data exploration and modeling, we exchange player1 and player2 for half of the matches and save it in another csv file.

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_csv('match_data_20_tourns.csv')

In [3]:
data.head()

,player1,player2,best_of,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,p1_frames_won,p2_matches_played,...,p1_frames_played_1_year,p1_frames_won_1_year,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,match_result,win_percentage
0,Long Zehuang,Haydon Pinhey,7,0.719210,0.604679,78,39,443,225,115,...,178,99,284,147,121,57,347,168,0.0,0.571429
1,Wang Yuchen,Andrew Pagett,7,0.500000,0.500000,100,37,626,268,352,...,74,38,158,89,144,65,417,170,0.0,0.800000
2,Daniel Womersley,Ben Mertens,7,0.300556,0.405524,109,53,551,266,107,...,86,40,180,89,136,67,471,240,0.0,0.800000
3,Jimmy White,Paul Deaville,7,0.561265,0.528095,1577,844,13093,6755,32,...,85,31,384,153,97,51,126,66,0.0,0.571429
4,Alexander Ursenbacher,Mostafa Dorgham,7,0.821305,0.663180,286,129,1728,829,25,...,113,56,400,196,108,41,154,53,0.0,0.800000

In [4]:
row = data.loc[0]

In [5]:
#We use random.shuffle to choose the indices of matches we want to modify.
match_index = list(range(len(data)))
random.shuffle(match_index)
modify_index = match_index[:len(data)//2]

In [6]:
modify_index[:5]

[283, 868, 1321, 1452, 807]

In [7]:
#Create a new dataframe df to store the modified data
df = data.loc[modify_index]

In [8]:
data.columns

Index(['player1', 'player2', 'best_of', 'elo_match_win_rate',
       'elo_frame_win_rate', 'p1_matches_played', 'p1_matches_won',
       'p1_frames_played', 'p1_frames_won', 'p2_matches_played',
       'p2_matches_won', 'p2_frames_played', 'p2_frames_won',
       'p1_frames_played_1_year', 'p1_frames_won_1_year',
       'p1_frames_played_3_years', 'p1_frames_won_3_years',
       'p2_frames_played_1_year', 'p2_frames_won_1_year',
       'p2_frames_played_3_years', 'p2_frames_won_3_years', 'match_result',
       'win_percentage'],
      dtype='object')

In [9]:
#Exchange the stats of player1 and player2
df['player1'], df['player2'] = df['player2'], df['player1']
df['elo_match_win_rate'], df['elo_frame_win_rate'] = 1-df['elo_match_win_rate'], 1-df['elo_frame_win_rate']
df['p1_matches_played'], df['p1_matches_won'], df['p2_matches_played'], df['p2_matches_won'] = df['p2_matches_played'], df['p2_matches_won'], df['p1_matches_played'], df['p1_matches_won']
df['p1_frames_played'], df['p1_frames_won'], df['p2_frames_played'], df['p2_frames_won'] = df['p2_frames_played'], df['p2_frames_won'], df['p1_frames_played'], df['p1_frames_won']
df['p1_frames_played_1_year'], df['p1_frames_won_1_year'], df['p2_frames_played_1_year'], df['p2_frames_won_1_year'] = df['p2_frames_played_1_year'], df['p2_frames_won_1_year'], df['p1_frames_played_1_year'], df['p1_frames_won_1_year']
df['p1_frames_played_3_years'], df['p1_frames_won_3_years'], df['p2_frames_played_3_years'], df['p2_frames_won_3_years'] = df['p2_frames_played_3_years'], df['p2_frames_won_3_years'], df['p1_frames_played_3_years'], df['p1_frames_won_3_years']

df['match_result'] = 1
df['win_percentage'] = 1 - df['win_percentage']

In [10]:
data.loc[modify_index] = df

In [11]:
data.head()

,player1,player2,best_of,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,p1_frames_won,p2_matches_played,...,p1_frames_played_1_year,p1_frames_won_1_year,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,match_result,win_percentage
0,Long Zehuang,Haydon Pinhey,7,0.719210,0.604679,78,39,443,225,115,...,178,99,284,147,121,57,347,168,0.0,0.571429
1,Andrew Pagett,Wang Yuchen,7,0.500000,0.500000,352,153,2250,1055,100,...,144,65,417,170,74,38,158,89,1.0,0.200000
2,Ben Mertens,Daniel Womersley,7,0.699444,0.594476,107,50,642,322,109,...,136,67,471,240,86,40,180,89,1.0,0.200000
3,Jimmy White,Paul Deaville,7,0.561265,0.528095,1577,844,13093,6755,32,...,85,31,384,153,97,51,126,66,0.0,0.571429
4,Alexander Ursenbacher,Mostafa Dorgham,7,0.821305,0.663180,286,129,1728,829,25,...,113,56,400,196,108,41,154,53,0.0,0.800000

In [12]:
data.to_csv('match_data_20_tourns_modified.csv', index=False)