In this notebook, we use the elo rating system to generate statistics of players from past matches.  
Columns: ['elo_win_rate', 'p1_frames_played', 'p1_frames_won', 'p2_frames_played', 'p2_frames_won',
            'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p2_frames_played_1_year','p2_frames_won_1_year',
            'p1_frames_played_3_years', 'p1_frames_won_3_years', 'p2_frames_played_3_years','p2_frames_won_3_years']

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import professional snooker matches data form 1982 to 2025
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/Data/matches.csv')
matches.head()

,player1,player2,score1,score2,best_of,tournament_id,date,year
0,Colin Roscoe,Jackie Rea,9,6,17,753,NaN,1982
1,Tommy Murphy,Clive Everton,9,4,17,753,NaN,1982
2,Vic Harris,Marcus Owen,9,4,17,753,NaN,1982
3,Bob Harris,Graham Cripsey,9,6,17,753,NaN,1982
4,Geoff Foulds,Matt Gibson,9,3,17,753,NaN,1982

In [ ]:
# We generate statistics for the 750th, 999th, 1040th, 1080th tournament in our dataset.
from elo_v4 import elo_rating

#Store all the tournaments in a list
tournaments = list(matches.tournament_id.unique())
#nth means nth tournament among 1085 tournaments
nth = range(1065, 1085)


data = pd.DataFrame(columns = ['player1', 'player2', 'best_of', 'elo_match_win_rate', 'elo_frame_win_rate',
                                        'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                        'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                        'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                        'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                        'match_result', 'win_percentage'])



for n in nth:
  past_tournaments = tournaments[:n]
  print(f'Generating data for the {n}th tournament')
  current = tournaments[n]
  past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
  
  matches_past = matches[past_index]
  matches_future = matches[matches['tournament_id'] == current]
  matches_future_X = matches_future[['player1', 'player2', 'best_of']]

  #Update statistics of players
  elo = elo_rating()
  elo.update_stats(matches = matches_past)
  stats = elo.stats
  sby = elo.stats_by_years
  player_stats = elo.generate_stats(matches_future_X)

  results = np.zeros(len(matches_future))
  win_perc = matches_future['score1'] / (matches_future['score1'] + matches_future['score2'])

  
  new_data = player_stats
  new_data['match_result'] = results
  new_data['win_percentage'] = win_perc.values

  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 1065th tournament

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_5815/1133448099.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 1066th tournament
Generating data for the 1067th tournament
Generating data for the 1068th tournament
Generating data for the 1069th tournament
Generating data for the 1070th tournament
Generating data for the 1071th tournament
Generating data for the 1072th tournament
Generating data for the 1073th tournament
Generating data for the 1074th tournament

In [4]:
data.sample(5)

,player1,player2,best_of,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,p1_frames_won,p2_matches_played,...,p1_frames_played_1_year,p1_frames_won_1_year,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,match_result,win_percentage
447,Fan Zhengyi,Florian Nüßle,11,0.797124,0.620695,200,89,1274,593,78,...,260,140,773,407,52,27,199,117,0.0,0.750000
525,Judd Trump,Barry Hawkins,19,0.800149,0.594476,1484,1069,10282,6221,1365,...,623,392,1844,1132,356,193,1039,591,0.0,0.555556
451,Zhao Xintong,Noppon Saengkham,11,0.615028,0.543018,361,210,2309,1279,477,...,0,0,359,209,246,125,871,465,0.0,0.750000
373,Mark Selby,Shaun Murphy,7,0.500000,0.500000,1585,1082,11323,6589,1384,...,455,257,1385,787,357,201,1029,586,0.0,0.666667
941,Si Jiahui,Jak Jones,5,0.470732,0.484380,215,122,1447,777,427,...,19,9,833,461,29,18,773,427,0.0,0.600000

In [5]:
data

,player1,player2,best_of,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,p1_frames_won,p2_matches_played,...,p1_frames_played_1_year,p1_frames_won_1_year,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,match_result,win_percentage
0,Long Zehuang,Haydon Pinhey,7,0.719210,0.604679,78,39,443,225,115,...,178,99,284,147,121,57,347,168,0.0,0.571429
1,Wang Yuchen,Andrew Pagett,7,0.500000,0.500000,100,37,626,268,352,...,74,38,158,89,144,65,417,170,0.0,0.800000
2,Daniel Womersley,Ben Mertens,7,0.300556,0.405524,109,53,551,266,107,...,86,40,180,89,136,67,471,240,0.0,0.800000
3,Jimmy White,Paul Deaville,7,0.561265,0.528095,1577,844,13093,6755,32,...,85,31,384,153,97,51,126,66,0.0,0.571429
4,Alexander Ursenbacher,Mostafa Dorgham,7,0.821305,0.663180,286,129,1728,829,25,...,113,56,400,196,108,41,154,53,0.0,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,Xiao Guodong,Matthew Selt,5,0.684438,0.601088,792,462,5012,2756,899,...,50,31,876,483,16,6,803,418,0.0,1.000000
1088,Xiao Guodong,Kyren Wilson,5,0.411734,0.452642,792,462,5012,2756,1092,...,50,31,876,483,82,50,1211,713,0.0,1.000000
1089,Kyren Wilson,Judd Trump,5,0.450917,0.473774,1092,701,7000,3967,1496,...,82,50,1211,713,37,24,1356,853,0.0,1.000000
1090,Mark Selby,Hossein Vafaei,5,0.595095,0.551071,1599,1090,11394,6625,352,...,32,16,1081,607,25,13,690,389,0.0,0.750000
1091,Mark Selby,Kyren Wilson,5,0.345101,0.415809,1599,1090,11394,6625,1092,...,32,16,1081,607,82,50,1211,713,0.0,1.000000

In [ ]:
data.to_csv('match_data_20_tourns.csv', index=False)