In this notebook, we use the elo rating system to generate statistics of players from past matches.  
Columns: ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo'
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage']

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import professional snooker matches data form 1982 to 2025
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/1_Match_Data/matches.csv')
matches.head()

,player1,player2,score1,score2,best_of,tournament_id,date,year
0,Colin Roscoe,Jackie Rea,9,6,17,753,NaN,1982
1,Tommy Murphy,Clive Everton,9,4,17,753,NaN,1982
2,Vic Harris,Marcus Owen,9,4,17,753,NaN,1982
3,Bob Harris,Graham Cripsey,9,6,17,753,NaN,1982
4,Geoff Foulds,Matt Gibson,9,3,17,753,NaN,1982

In [3]:
# We generate statistics for the 750th, 999th, 1040th, 1080th tournament in our dataset.
from elo_v4 import elo_rating

#Store all the tournaments in a list
tournaments = list(matches.tournament_id.unique())
#nth means nth tournament among 1085 tournaments
nth = range(1035,1085)


data = pd.DataFrame(columns = ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage'])



for n in nth:
  past_tournaments = tournaments[:n]
  print(f'Generating data for the {n}th tournament')
  current = tournaments[n]
  past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
  
  matches_past = matches[past_index]
  matches_future = matches[matches['tournament_id'] == current]
  matches_future_X = matches_future[['player1', 'player2', 'best_of']]

  #Update statistics of players
  elo = elo_rating()
  elo.update_stats(matches = matches_past)
  stats = elo.stats
  sby = elo.stats_by_years
  player_stats = elo.generate_stats(matches_future_X)

  results = np.zeros(len(matches_future))
  win_perc = matches_future['score1'] / (matches_future['score1'] + matches_future['score2'])

  
  new_data = player_stats
  new_data['score1'] = matches_future['score1'].values
  new_data['score2'] = matches_future['score2'].values
  new_data['match_result'] = results
  new_data['win_percentage'] = win_perc.values
  

  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 1035th tournament

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_1617/4191801276.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 1036th tournament
Generating data for the 1037th tournament
Generating data for the 1038th tournament
Generating data for the 1039th tournament
Generating data for the 1040th tournament
Generating data for the 1041th tournament
Generating data for the 1042th tournament
Generating data for the 1043th tournament
Generating data for the 1044th tournament
Generating data for the 1045th tournament
Generating data for the 1046th tournament
Generating data for the 1047th tournament
Generating data for the 1048th tournament
Generating data for the 1049th tournament
Generating data for the 1050th tournament
Generating data for the 1051th tournament
Generating data for the 1052th tournament
Generating data for the 1053th tournament
Generating data for the 1054th tournament
Generating data for the 1055th tournament
Generating data for the 1056th tournament
Generating data for the 1057th tournament
Generating data for the 1058th tournament
Generating data for the 1059th tournament
Generating data for the 1060th tournament
Generating data for the 1061th tournament
Generating data for the 1062th tournament
Generating data for the 1063th tournament
Generating data for the 1064th tournament
Generating data for the 1065th tournament
Generating data for the 1066th tournament
Generating data for the 1067th tournament
Generating data for the 1068th tournament
Generating data for the 1069th tournament
Generating data for the 1070th tournament
Generating data for the 1071th tournament
Generating data for the 1072th tournament
Generating data for the 1073th tournament
Generating data for the 1074th tournament
Generating data for the 1075th tournament
Generating data for the 1076th tournament
Generating data for the 1077th tournament
Generating data for the 1078th tournament
Generating data for the 1079th tournament
Generating data for the 1080th tournament
Generating data for the 1081th tournament
Generating data for the 1082th tournament
Generating data for the 1083th tournament
Generating data for the 1084th tournament

In [4]:
data.sample(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
3112,Mark Allen,Long Zehuang,7,1548,1319,0.782217,0.639340,1086,722,7693,...,1185,676,165,92,271,140,4,3,0.0,0.571429
3795,Tom Ford,Wu Yize,1,1346,1455,0.432293,0.432293,956,542,6515,...,1005,522,345,191,777,418,1,0,0.0,1.000000
2947,Thepchaiya Un-Nooh,Artemijs Zizins,7,1465,1099,0.891413,0.714022,568,332,3917,...,664,364,69,40,69,40,4,1,0.0,0.800000
2762,Thepchaiya Un-Nooh,Alexander Ursenbacher,7,1441,1328,0.650487,0.570159,564,329,3894,...,641,349,90,47,377,187,4,1,0.0,0.800000
3716,Gerard Greene,Robbie Mcguigan,1,1154,1054,0.562177,0.562177,838,427,5998,...,217,90,98,39,239,102,1,0,0.0,1.000000

In [5]:
data

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
0,Cao Yupeng,Jiang Jun,9,1411,1044,0.918016,0.714532,341,179,2302,...,446,242,32,17,32,17,5,0,0.0,1.000000
1,Zhou Yuelong,Siripaporn Nuanthakhamjan,9,1384,965,0.943119,0.740295,459,272,2879,...,808,430,23,4,23,4,5,2,0.0,0.714286
2,Wu Yize,Allan Taylor,9,1342,1237,0.656987,0.565251,78,37,552,...,404,215,101,49,336,147,5,3,0.0,0.625000
3,Ben Woollaston,Oliver Brown,9,1412,1146,0.845318,0.660383,803,454,5053,...,534,282,91,35,235,97,5,2,0.0,0.714286
4,Mark Williams,Andres Petrov,9,1611,1045,0.982235,0.804553,1751,1151,12775,...,1112,649,79,25,167,61,5,2,0.0,0.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5053,Connor Benzey,John Astley,7,1083,1245,0.290008,0.400112,38,19,195,...,87,52,11,7,241,108,4,2,0.0,0.666667
5054,Fergal Quinn (II),Dean Young,7,1049,1110,0.417243,0.461949,43,20,229,...,124,62,72,32,400,172,4,1,0.0,0.800000
5055,David Grace,Jack Borwick,7,1244,976,0.818679,0.661503,504,232,3294,...,432,199,8,4,67,26,4,0,0.0,1.000000
5056,Ian Burns,Andrew Pagett,7,1278,1094,0.734971,0.613014,520,252,3294,...,439,216,37,13,390,160,4,1,0.0,0.800000
5057,Connor Benzey,Rodion Judin,7,1083,961,0.661777,0.575664,38,19,195,...,87,52,6,2,49,19,4,2,0.0,0.666667

In [6]:
data.to_csv('match_data_50_tourns.csv', index=False)