In this notebook, we use the elo rating system to generate statistics of players from past matches.  
Columns: ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo'
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage']

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import professional snooker matches data form 1982 to 2025
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/1_Match_Data/matches.csv')
matches.head()

,player1,player2,score1,score2,best_of,tournament_id,date,year
0,Colin Roscoe,Jackie Rea,9,6,17,753,NaN,1982
1,Tommy Murphy,Clive Everton,9,4,17,753,NaN,1982
2,Vic Harris,Marcus Owen,9,4,17,753,NaN,1982
3,Bob Harris,Graham Cripsey,9,6,17,753,NaN,1982
4,Geoff Foulds,Matt Gibson,9,3,17,753,NaN,1982

In [3]:
# We generate statistics for the 750th, 999th, 1040th, 1080th tournament in our dataset.
from elo_v4 import elo_rating

#Store all the tournaments in a list
tournaments = list(matches.tournament_id.unique())
#nth means nth tournament among 1085 tournaments
nth = range(1065,1085)


data = pd.DataFrame(columns = ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage'])



for n in nth:
  past_tournaments = tournaments[:n]
  print(f'Generating data for the {n}th tournament')
  current = tournaments[n]
  past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
  
  matches_past = matches[past_index]
  matches_future = matches[matches['tournament_id'] == current]
  matches_future_X = matches_future[['player1', 'player2', 'best_of']]

  #Update statistics of players
  elo = elo_rating()
  elo.update_stats(matches = matches_past)
  stats = elo.stats
  sby = elo.stats_by_years
  player_stats = elo.generate_stats(matches_future_X)

  results = np.zeros(len(matches_future))
  win_perc = matches_future['score1'] / (matches_future['score1'] + matches_future['score2'])

  
  new_data = player_stats
  new_data['score1'] = matches_future['score1'].values
  new_data['score2'] = matches_future['score2'].values
  new_data['match_result'] = results
  new_data['win_percentage'] = win_perc.values
  

  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 1065th tournament

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_7080/2350635564.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 1066th tournament
Generating data for the 1067th tournament
Generating data for the 1068th tournament
Generating data for the 1069th tournament
Generating data for the 1070th tournament
Generating data for the 1071th tournament
Generating data for the 1072th tournament
Generating data for the 1073th tournament
Generating data for the 1074th tournament
Generating data for the 1075th tournament
Generating data for the 1076th tournament
Generating data for the 1077th tournament
Generating data for the 1078th tournament
Generating data for the 1079th tournament
Generating data for the 1080th tournament
Generating data for the 1081th tournament
Generating data for the 1082th tournament
Generating data for the 1083th tournament
Generating data for the 1084th tournament

In [4]:
data.sample(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
766,Kyren Wilson,Anthony McGill,9,1633,1354,0.856635,0.667633,1082,693,6911,...,1604,943,161,77,713,382,5,4,0.0,0.555556
461,Jackson Page,Jamie Clarke,11,1395,1266,0.707443,0.579933,218,112,1400,...,694,360,175,81,593,286,6,4,0.0,0.600000
391,Chris Totten,Ryan Davies,11,1124,1120,0.506767,0.502500,107,38,614,...,228,117,38,22,155,78,6,2,0.0,0.750000
1879,Ian Burns,Billy Joe Castle,7,1278,1140,0.681467,0.585405,520,252,3294,...,439,216,20,13,79,43,4,2,0.0,0.666667
1415,Chris Wakelin,Mark Allen,25,1426,1520,0.276681,0.441519,481,259,3053,...,968,523,86,45,1025,575,13,6,0.0,0.684211

In [5]:
data

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_played_3_years,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage
0,Long Zehuang,Haydon Pinhey,7,1328,1158,0.719210,0.604679,78,39,443,...,284,147,121,57,347,168,4,3,0.0,0.571429
1,Wang Yuchen,Andrew Pagett,7,1162,1162,0.500000,0.500000,100,37,626,...,158,89,144,65,417,170,4,1,0.0,0.800000
2,Daniel Womersley,Ben Mertens,7,1109,1262,0.300556,0.405524,109,53,551,...,180,89,136,67,471,240,4,1,0.0,0.800000
3,Jimmy White,Paul Deaville,7,1141,1096,0.561265,0.528095,1577,844,13093,...,384,153,97,51,126,66,4,3,0.0,0.571429
4,Alexander Ursenbacher,Mostafa Dorgham,7,1302,1031,0.821305,0.663180,286,129,1728,...,400,196,108,41,154,53,4,1,0.0,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,Connor Benzey,John Astley,7,1083,1245,0.290008,0.400112,38,19,195,...,87,52,11,7,241,108,4,2,0.0,0.666667
1910,Fergal Quinn (II),Dean Young,7,1049,1110,0.417243,0.461949,43,20,229,...,124,62,72,32,400,172,4,1,0.0,0.800000
1911,David Grace,Jack Borwick,7,1244,976,0.818679,0.661503,504,232,3294,...,432,199,8,4,67,26,4,0,0.0,1.000000
1912,Ian Burns,Andrew Pagett,7,1278,1094,0.734971,0.613014,520,252,3294,...,439,216,37,13,390,160,4,1,0.0,0.800000
1913,Connor Benzey,Rodion Judin,7,1083,961,0.661777,0.575664,38,19,195,...,87,52,6,2,49,19,4,2,0.0,0.666667

In [6]:
data.to_csv('match_data_20_tourns.csv', index=False)