Attempt to find players who involved in match fixing by looking at those who lose frequent to players with much lower elo-rating.

In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/1_Match_Data/matches.csv')

In [3]:
from elo import elo_rating
elo = elo_rating()
elo.update_stats(matches = matches, difference = 100)
stats = elo.stats

/Users/tliu/Desktop/Erdos Project/Match_Fixing_Exploration/elo.py:99: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.         0.125      0.5        ... 0.33333333 0.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'matches_win_rate'] = df.loc[:, 'matches_won']/(df.loc[:, 'matches_played'])
/Users/tliu/Desktop/Erdos Project/Match_Fixing_Exploration/elo.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.4        0.35416667 0.44444444 ... 0.42857143 0.         0.14285714]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'frames_win_rate'] = df.loc[:, 'frames_won']/(df.loc[:, 'frames_played'])

In [4]:
stats

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss
A Barrett,996,1,0,0.000000,5,2,0.400000,0
A Bulajiang,1010,8,1,0.125000,48,17,0.354167,0
A Chan,995,2,1,0.500000,9,4,0.444444,0
A Coleman,992,1,0,0.000000,6,2,0.333333,0
A Noad,988,1,0,0.000000,3,0,0.000000,0
...,...,...,...,...,...,...,...,...
Zsolt Fenyvesi,961,4,0,0.000000,21,5,0.238095,0
Zulfigar Cheema,843,9,0,0.000000,53,8,0.150943,0
Zulfiqar Qadir,997,6,2,0.333333,35,15,0.428571,0
Zung Chun Hong,996,1,0,0.000000,2,0,0.000000,0
Özyurt Aksoy,960,3,0,0.000000,14,2,0.142857,0

In [5]:
stats = stats.sort_values(by = 'big_loss', ascending=False)
stats

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss
Jimmy White,1118,1593,851,0.534212,13212,6809,0.515365,104
Fergal O'Brien,1168,1030,561,0.544660,7517,3903,0.519223,70
Matthew Selt,1408,926,502,0.542117,5952,3097,0.520329,70
Dominic Dale,1243,1130,626,0.553982,7824,4105,0.524668,68
Anthony Hamilton,1206,1070,602,0.562617,7838,4115,0.525006,66
...,...,...,...,...,...,...,...,...
Johan Somers,980,2,0,0.000000,11,3,0.272727,0
Johan van Goetham,955,34,14,0.411765,235,108,0.459574,0
Johannes Oswald,992,1,0,0.000000,6,2,0.333333,0
John Auchterlonie,995,2,1,0.500000,13,6,0.461538,0
Özyurt Aksoy,960,3,0,0.000000,14,2,0.142857,0

In [6]:
stats['big_loss_perc'] = stats['big_loss']/stats['matches_played']
stats1 = stats[stats['matches_played']>100].sort_values(by = 'big_loss_perc', ascending=False)
stats1[:20]

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss,big_loss_perc
Passakorn Suwannawat,1159,106,35,0.330189,754,330,0.437666,20,0.188679
Andrew Milliard,816,190,54,0.284211,1095,412,0.376256,35,0.184211
Zhang Yong,1166,136,56,0.411765,826,355,0.429782,25,0.183824
Mei Xiwen,1372,161,80,0.496894,1062,532,0.500942,29,0.180124
Luo Honghao,1216,132,63,0.477273,777,376,0.483912,23,0.174242
Aaron Hill,1382,151,72,0.476821,918,453,0.493464,25,0.165563
Wang Yuchen,1278,121,49,0.404959,795,356,0.447799,20,0.165289
Xu Si,1332,232,104,0.448276,1516,709,0.467678,38,0.163793
Pat Houlihan,890,116,36,0.310345,933,383,0.410504,19,0.163793
Li Yan,1145,129,56,0.434109,885,425,0.480226,21,0.162791
Iulian Boiko,1209,124,47,0.379032,730,322,0.441096,20,0.161290
Ben Hancorn,1191,113,51,0.451327,581,284,0.488812,18,0.159292
Pankaj Advani,1397,114,67,0.587719,791,434,0.548673,18,0.157895
Soheil Vahedi,1172,140,52,0.371429,824,358,0.434466,22,0.157143
Chris Totten,1146,115,41,0.356522,680,280,0.411765,18,0.156522
Igor Figueiredo,1217,155,70,0.451613,1074,493,0.459032,24,0.154839
Peifan Lei,1392,151,76,0.503311,982,483,0.491853,23,0.152318
Tony Kearney,896,132,42,0.318182,1086,458,0.421731,20,0.151515
Ben Mertens,1232,121,55,0.454545,751,373,0.496671,18,0.148760
Dessie Sheehan,687,184,37,0.201087,1349,489,0.362491,27,0.146739

In [7]:
stats2 = stats[stats['matches_played']>200]
stats2[:20]

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss,big_loss_perc
Jimmy White,1118,1593,851,0.534212,13212,6809,0.515365,104,0.065286
Fergal O'Brien,1168,1030,561,0.544660,7517,3903,0.519223,70,0.067961
Matthew Selt,1408,926,502,0.542117,5952,3097,0.520329,70,0.075594
Dominic Dale,1243,1130,626,0.553982,7824,4105,0.524668,68,0.060177
Anthony Hamilton,1206,1070,602,0.562617,7838,4115,0.525006,66,0.061682
Michael White,1319,702,384,0.547009,4536,2358,0.519841,64,0.091168
Peter Ebdon,1333,1130,644,0.569912,8841,4739,0.536025,64,0.056637
Martin Gould,1311,890,525,0.589888,5809,3144,0.541229,63,0.070787
Ryan Day,1399,1355,798,0.588930,8935,4856,0.543481,63,0.046494
Ben Woollaston,1426,861,485,0.563298,5492,2917,0.531136,62,0.072009
Michael Holt,1359,1039,586,0.564004,7243,3823,0.527820,61,0.058710
Robert Milkins,1297,1172,671,0.572526,8082,4297,0.531675,61,0.052048
James Wattana,1277,846,450,0.531915,7066,3671,0.519530,61,0.072104
Ken Doherty,1156,1296,746,0.575617,10197,5473,0.536726,61,0.047068
Mark King,1273,1105,603,0.545701,7892,4124,0.522554,60,0.054299
Joe Perry,1281,1405,811,0.577224,9652,5201,0.538852,60,0.042705
Alan McManus,1311,1009,587,0.581764,8285,4382,0.528908,58,0.057483
Peter Lines,1211,927,480,0.517799,6516,3332,0.511357,57,0.061489
Barry Pinches,1157,887,447,0.503946,6539,3347,0.511852,57,0.064262
Alfie Burden,1228,835,432,0.517365,5909,2994,0.506685,57,0.068263

In [8]:
match_fixers = ['Liang Wenbo', 'Li Hang', 'Lu Ning', 'Yan Bingtao', 'Zhao Xintong',
                 'Chang Bingyu', 'Bai Langning', 'Chen Zifan', 'Zhang Jiankang',
                 'Stephen Lee', 'Mark King', 'David John','Jamie Jones']
stats3 = stats.loc[match_fixers]
stats3

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss,big_loss_perc
Liang Wenbo,1458,769,457,0.594278,5250,2876,0.547810,41,0.053316
Li Hang,1394,412,216,0.524272,2802,1449,0.517131,41,0.099515
Lu Ning,1340,262,127,0.484733,1599,793,0.495935,20,0.076336
Yan Bingtao,1574,354,232,0.655367,2479,1406,0.567164,21,0.059322
Zhao Xintong,1620,375,223,0.594667,2525,1419,0.561980,23,0.061333
Chang Bingyu,1263,90,35,0.388889,547,251,0.458867,14,0.155556
Bai Langning,1185,61,20,0.327869,371,160,0.431267,11,0.180328
Chen Zifan,1101,174,69,0.396552,988,422,0.427126,20,0.114943
Zhang Jiankang,1126,73,20,0.273973,429,163,0.379953,15,0.205479
Stephen Lee,1478,711,451,0.634318,5650,3158,0.558938,14,0.019691
Mark King,1273,1105,603,0.545701,7892,4124,0.522554,60,0.054299
David John,1093,99,41,0.414141,645,293,0.454264,9,0.090909
Jamie Jones,1299,698,409,0.585960,4580,2454,0.535808,38,0.054441

In [10]:
stats.sort_values(by = 'elo_rating', ascending=False).iloc[:100]['big_loss_perc'].describe()

count    100.000000
mean       0.077319
std        0.045799
min        0.007243
25%        0.045138
50%        0.068261
75%        0.104541
max        0.206186
Name: big_loss_perc, dtype: float64

We do see some matches fixers with high ratio of big loss (losing to a player with elo 100 less). However, they also have low matches sample. So the high ratio might be because there are not enough matches to establish their elo rating.