Attempt to find players who involved in match fixing by looking at those who lose frequent to players with much lower elo-rating.

In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/Data/matches.csv')

In [3]:
from elo import elo_rating
elo = elo_rating()
elo.update_stats(matches = matches, difference = 50)
stats = elo.stats

/Users/tliu/Desktop/Erdos Project/Match_Fixing/elo.py:99: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.         0.125      0.5        ... 0.33333333 0.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'matches_win_rate'] = df.loc[:, 'matches_won']/(df.loc[:, 'matches_played'])
/Users/tliu/Desktop/Erdos Project/Match_Fixing/elo.py:102: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.4        0.35416667 0.44444444 ... 0.42857143 0.         0.14285714]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'frames_win_rate'] = df.loc[:, 'frames_won']/(df.loc[:, 'frames_played'])

In [4]:
stats

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss
A Barrett,996,1,0,0.000000,5,2,0.400000,0
A Bulajiang,1010,8,1,0.125000,48,17,0.354167,0
A Chan,995,2,1,0.500000,9,4,0.444444,0
A Coleman,992,1,0,0.000000,6,2,0.333333,0
A Noad,988,1,0,0.000000,3,0,0.000000,0
...,...,...,...,...,...,...,...,...
Zsolt Fenyvesi,961,4,0,0.000000,21,5,0.238095,0
Zulfigar Cheema,843,9,0,0.000000,53,8,0.150943,0
Zulfiqar Qadir,997,6,2,0.333333,35,15,0.428571,0
Zung Chun Hong,996,1,0,0.000000,2,0,0.000000,0
Özyurt Aksoy,960,3,0,0.000000,14,2,0.142857,0

In [5]:
stats = stats.sort_values(by = 'big_loss', ascending=False)
stats

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss
Jimmy White,1118,1593,851,0.534212,13212,6809,0.515365,171
Joe Perry,1281,1405,811,0.577224,9652,5201,0.538852,139
Ryan Day,1399,1355,798,0.588930,8935,4856,0.543481,127
Fergal O'Brien,1168,1030,561,0.544660,7517,3903,0.519223,119
Ken Doherty,1156,1296,746,0.575617,10197,5473,0.536726,118
...,...,...,...,...,...,...,...,...
John Patrick Tyndall,1006,3,2,0.666667,17,9,0.529412,0
John Patterson,987,1,0,0.000000,6,1,0.166667,0
John Phillips,965,2,0,0.000000,21,6,0.285714,0
John Robertson,988,1,0,0.000000,7,2,0.285714,0
Özyurt Aksoy,960,3,0,0.000000,14,2,0.142857,0

In [6]:
stats['big_loss_perc'] = stats['big_loss']/stats['matches_played']
stats1 = stats.sort_values(by = 'big_loss_perc', ascending=False)
stats1[:20]

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss,big_loss_perc
Wayne Greenwood,1011,4,2,0.500000,19,10,0.526316,2,0.500000
Panompai Powises,1091,8,4,0.500000,69,33,0.478261,4,0.500000
Praprut Chaithanasak,1013,2,1,0.500000,17,8,0.470588,1,0.500000
Jamie Barratt,1001,2,1,0.500000,12,5,0.416667,1,0.500000
Liu Fan,1015,4,2,0.500000,21,10,0.476190,2,0.500000
Surathep Phuchalaem,1014,2,1,0.500000,16,7,0.437500,1,0.500000
Huang Zhong,1009,2,1,0.500000,13,6,0.461538,1,0.500000
Lin Kuan,1005,2,1,0.500000,4,2,0.500000,1,0.500000
Jason Cheshire,1015,4,2,0.500000,28,12,0.428571,2,0.500000
Scott Nicholson,1008,4,2,0.500000,31,16,0.516129,2,0.500000
Xu Jianhao,1018,4,2,0.500000,28,14,0.500000,2,0.500000
E Loh,1006,2,1,0.500000,4,2,0.500000,1,0.500000
Tanel Miah,994,7,3,0.428571,55,24,0.436364,3,0.428571
Ishpreet Chadha,1029,7,3,0.428571,45,19,0.422222,3,0.428571
Gareth Coates,1029,22,11,0.500000,147,69,0.469388,9,0.409091
Tom Gleeson,999,5,2,0.400000,28,12,0.428571,2,0.400000
Alex Pagulayan,1069,13,7,0.538462,74,37,0.500000,5,0.384615
Poramin Danjirakul,1031,8,4,0.500000,46,22,0.478261,3,0.375000
Anthony Bolsover,1094,14,9,0.642857,93,51,0.548387,5,0.357143
Somporn Kanthawung,1086,15,6,0.400000,138,68,0.492754,5,0.333333

In [7]:
stats2 = stats[stats['matches_played']>200]
stats2[:20]

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss,big_loss_perc
Jimmy White,1118,1593,851,0.534212,13212,6809,0.515365,171,0.107345
Joe Perry,1281,1405,811,0.577224,9652,5201,0.538852,139,0.098932
Ryan Day,1399,1355,798,0.588930,8935,4856,0.543481,127,0.093727
Fergal O'Brien,1168,1030,561,0.544660,7517,3903,0.519223,119,0.115534
Ken Doherty,1156,1296,746,0.575617,10197,5473,0.536726,118,0.091049
Mark Davis,1347,1338,793,0.592676,9203,5000,0.543301,118,0.088191
Robert Milkins,1297,1172,671,0.572526,8082,4297,0.531675,116,0.098976
Michael Holt,1359,1039,586,0.564004,7243,3823,0.527820,113,0.108758
Anthony Hamilton,1206,1070,602,0.562617,7838,4115,0.525006,113,0.105607
Dominic Dale,1243,1130,626,0.553982,7824,4105,0.524668,113,0.100000
Matthew Selt,1408,926,502,0.542117,5952,3097,0.520329,110,0.118790
Mark King,1273,1105,603,0.545701,7892,4124,0.522554,109,0.098643
Michael White,1319,702,384,0.547009,4536,2358,0.519841,108,0.153846
Ricky Walden,1357,1197,709,0.592314,8051,4400,0.546516,107,0.089390
Marco Fu,1363,989,576,0.582406,7380,3995,0.541328,106,0.107179
Peter Ebdon,1333,1130,644,0.569912,8841,4739,0.536025,106,0.093805
Peter Lines,1211,927,480,0.517799,6516,3332,0.511357,104,0.112190
Nigel Bond,1193,966,513,0.531056,7401,3820,0.516146,103,0.106625
Ben Woollaston,1426,861,485,0.563298,5492,2917,0.531136,103,0.119628
Graeme Dott,1317,1203,700,0.581879,8600,4620,0.537209,102,0.084788

In [8]:
match_fixers = ['Liang Wenbo', 'Li Hang', 'Lu Ning', 'Yan Bingtao', 'Zhao Xintong',
                 'Chang Bingyu', 'Bai Langning', 'Chen Zifan', 'Zhang Jiankang',
                 'Stephen Lee', 'Mark King', 'David John','Jamie Jones']
stats3 = stats.loc[match_fixers]
stats3

,elo_rating,matches_played,matches_won,matches_win_rate,frames_played,frames_won,frames_win_rate,big_loss,big_loss_perc
Liang Wenbo,1458,769,457,0.594278,5250,2876,0.547810,69,0.089727
Li Hang,1394,412,216,0.524272,2802,1449,0.517131,53,0.128641
Lu Ning,1340,262,127,0.484733,1599,793,0.495935,27,0.103053
Yan Bingtao,1574,354,232,0.655367,2479,1406,0.567164,39,0.110169
Zhao Xintong,1620,375,223,0.594667,2525,1419,0.561980,33,0.088000
Chang Bingyu,1263,90,35,0.388889,547,251,0.458867,19,0.211111
Bai Langning,1185,61,20,0.327869,371,160,0.431267,13,0.213115
Chen Zifan,1101,174,69,0.396552,988,422,0.427126,24,0.137931
Zhang Jiankang,1126,73,20,0.273973,429,163,0.379953,17,0.232877
Stephen Lee,1478,711,451,0.634318,5650,3158,0.558938,46,0.064698
Mark King,1273,1105,603,0.545701,7892,4124,0.522554,109,0.098643
David John,1093,99,41,0.414141,645,293,0.454264,13,0.131313
Jamie Jones,1299,698,409,0.585960,4580,2454,0.535808,62,0.088825

In [9]:
stats.sort_values(by = 'elo_rating', ascending=False).iloc[:30]['big_loss_perc'].mean()

np.float64(0.09179390634538094)