In this notebook, we use the elo rating system to generate statistics of players from past matches.  
Columns: ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo'
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage']

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import professional snooker matches data form 1982 to 2025
matches = pd.read_csv('/Users/tliu/Desktop/Erdos Project/1_Match_Data/matches.csv')
matches.head()

,player1,player2,score1,score2,best_of,tournament_id,date,year
0,Colin Roscoe,Jackie Rea,9,6,17,753,NaN,1982
1,Tommy Murphy,Clive Everton,9,4,17,753,NaN,1982
2,Vic Harris,Marcus Owen,9,4,17,753,NaN,1982
3,Bob Harris,Graham Cripsey,9,6,17,753,NaN,1982
4,Geoff Foulds,Matt Gibson,9,3,17,753,NaN,1982

In [3]:
from elo_v4 import elo_rating

#Store all the tournaments in a list
tournaments = list(matches.tournament_id.unique())
#nth means nth tournament among 1085 tournaments
nth = range(785,835)


data = pd.DataFrame(columns = ['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
                               'elo_match_win_rate', 'elo_frame_win_rate',
                                'p1_matches_played', 'p1_matches_won', 'p1_frames_played', 'p1_frames_won', 
                                'p2_matches_played', 'p2_matches_won', 'p2_frames_played', 'p2_frames_won', 
                                'p1_frames_played_1_year', 'p1_frames_won_1_year', 'p1_frames_played_3_years', 'p1_frames_won_3_years',
                                'p2_frames_played_1_year','p2_frames_won_1_year', 'p2_frames_played_3_years','p2_frames_won_3_years',
                                'score1', 'score2','match_result', 'win_percentage', 'tournament_id'])



for n in nth:
  past_tournaments = tournaments[:n]
  print(f'Generating data for the {n}th tournament')
  current = tournaments[n]
  past_index = matches['tournament_id'].map(lambda x: x in past_tournaments)
  
  matches_past = matches[past_index]
  matches_future = matches[matches['tournament_id'] == current]
  matches_future_X = matches_future[['player1', 'player2', 'best_of']]

  #Update statistics of players
  elo = elo_rating()
  elo.update_stats(matches = matches_past)
  stats = elo.stats
  sby = elo.stats_by_years
  player_stats = elo.generate_stats(matches_future_X)

  results = np.zeros(len(matches_future))
  win_perc = matches_future['score1'] / (matches_future['score1'] + matches_future['score2'])

  
  new_data = player_stats
  new_data['score1'] = matches_future['score1'].values
  new_data['score2'] = matches_future['score2'].values
  new_data['match_result'] = results
  new_data['win_percentage'] = win_perc.values
  new_data['tournament_id'] = tournaments[n]
  

  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 785th tournament

/var/folders/pd/b57yb11s57b55h2t3r3c8q1r0000gn/T/ipykernel_4249/3406462505.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, new_data], axis = 0, ignore_index = True)

Generating data for the 786th tournament
Generating data for the 787th tournament
Generating data for the 788th tournament
Generating data for the 789th tournament
Generating data for the 790th tournament
Generating data for the 791th tournament
Generating data for the 792th tournament
Generating data for the 793th tournament
Generating data for the 794th tournament
Generating data for the 795th tournament
Generating data for the 796th tournament
Generating data for the 797th tournament
Generating data for the 798th tournament
Generating data for the 799th tournament
Generating data for the 800th tournament
Generating data for the 801th tournament
Generating data for the 802th tournament
Generating data for the 803th tournament
Generating data for the 804th tournament
Generating data for the 805th tournament
Generating data for the 806th tournament
Generating data for the 807th tournament
Generating data for the 808th tournament
Generating data for the 809th tournament
Generating data for the 810th tournament
Generating data for the 811th tournament
Generating data for the 812th tournament
Generating data for the 813th tournament
Generating data for the 814th tournament
Generating data for the 815th tournament
Generating data for the 816th tournament
Generating data for the 817th tournament
Generating data for the 818th tournament
Generating data for the 819th tournament
Generating data for the 820th tournament
Generating data for the 821th tournament
Generating data for the 822th tournament
Generating data for the 823th tournament
Generating data for the 824th tournament
Generating data for the 825th tournament
Generating data for the 826th tournament
Generating data for the 827th tournament
Generating data for the 828th tournament
Generating data for the 829th tournament
Generating data for the 830th tournament
Generating data for the 831th tournament
Generating data for the 832th tournament
Generating data for the 833th tournament
Generating data for the 834th tournament

In [4]:
data.sample(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
2938,Mark Selby,Dominic Dale,5,1604,1462,0.661324,0.587830,796,541,5821,...,1172,409,240,1214,652,3,0,0.0,1.000000,1005
6098,Sam Baird,Dave Harold,7,1290,1193,0.630066,0.560330,251,133,1701,...,415,27,11,380,182,4,0,0.0,1.000000,1083
4224,Ding Junhui,Ben Judge,9,1553,969,0.984781,0.811533,579,389,4271,...,701,0,0,53,20,5,0,0.0,1.000000,1272
2733,Joe Perry,Anthony McGill,9,1462,1375,0.631225,0.554162,801,468,5895,...,790,305,164,937,504,5,0,0.0,1.000000,992
1375,Stuart Bingham,Anthony Hamilton,9,1526,1338,0.764732,0.615384,777,488,5829,...,831,93,44,673,350,5,4,0.0,0.555556,1048

In [5]:
data

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Ricky Walden,Mark Allen,7,1418,1580,0.290008,0.400112,539,328,3930,...,557,41,24,985,596,4,0,0.0,1.000000,1063
1,Judd Trump,Stephen Maguire,7,1551,1563,0.483599,0.492501,521,340,3566,...,782,128,83,1272,739,4,1,0.0,0.800000,1063
2,Mark Selby,Steve Davis,7,1592,1246,0.878716,0.703704,736,495,5330,...,875,8,2,581,286,4,1,0.0,0.800000,1063
3,Neil Robertson,Ali Carter,7,1546,1544,0.502734,0.501250,621,402,4581,...,815,11,5,876,499,4,0,0.0,1.000000,1063
4,Ronnie O'Sullivan,Stuart Bingham,7,1663,1488,0.724894,0.607663,1006,762,8914,...,431,96,60,1203,680,4,2,0.0,0.666667,1063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6250,Shaun Murphy,Ronnie O'Sullivan,9,1569,1695,0.313906,0.421895,861,562,6335,...,955,117,74,876,578,5,4,0.0,0.555556,1072
6251,Stephen Maguire,Neil Robertson,9,1450,1601,0.280790,0.406730,774,514,5716,...,851,325,209,1734,1044,5,4,0.0,0.555556,1072
6252,Mark Selby,Stephen Maguire,11,1547,1450,0.659420,0.560330,870,591,6302,...,1060,296,156,1481,851,6,2,0.0,0.750000,1072
6253,Shaun Murphy,Liang Wenbo,11,1569,1435,0.714641,0.582975,861,562,6335,...,955,414,242,1162,668,6,4,0.0,0.600000,1072
6254,Mark Selby,Shaun Murphy,17,1547,1569,0.454200,0.486253,870,591,6302,...,1060,416,255,1626,955,9,7,0.0,0.562500,1072

In [6]:
data.to_csv('match_data_785_835_tourns.csv', index=False)