In the match data generated in data_generation.ipynb, player1 is always the winner. For the purpose of future data exploration and modeling, we exchange player1 and player2 for half of the matches and save it in another csv file.

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_csv('match_data_785_835_tourns.csv')

In [3]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Ricky Walden,Mark Allen,7,1418,1580,0.290008,0.400112,539,328,3930,...,557,41,24,985,596,4,0,0.0,1.000000,1063
1,Judd Trump,Stephen Maguire,7,1551,1563,0.483599,0.492501,521,340,3566,...,782,128,83,1272,739,4,1,0.0,0.800000,1063
2,Mark Selby,Steve Davis,7,1592,1246,0.878716,0.703704,736,495,5330,...,875,8,2,581,286,4,1,0.0,0.800000,1063
3,Neil Robertson,Ali Carter,7,1546,1544,0.502734,0.501250,621,402,4581,...,815,11,5,876,499,4,0,0.0,1.000000,1063
4,Ronnie O'Sullivan,Stuart Bingham,7,1663,1488,0.724894,0.607663,1006,762,8914,...,431,96,60,1203,680,4,2,0.0,0.666667,1063

In [4]:
row = data.loc[0]

In [5]:
#We use random.shuffle to choose the indices of matches we want to modify.
match_index = list(range(len(data)))
random.shuffle(match_index)
modify_index = match_index[:len(data)//2]

In [6]:
modify_index[:5]

[1547, 49, 4616, 1787, 2105]

In [7]:
data.loc[modify_index].head(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
1547,Fang Xiongman,Anthony Massey,7,1046,787,0.810645,0.656447,15,7,82,...,39,0,0,0,0,4,0,0.0,1.000000,1047
49,Mitchell Mann,Peter Lines,11,1158,1296,0.279664,0.414595,137,68,790,...,119,45,22,578,284,6,5,0.0,0.545455,1058
4616,Ben Woollaston,Vinnie Calabrese,7,1338,1070,0.818679,0.661503,413,237,2722,...,428,37,11,351,132,4,0,0.0,1.000000,1110
1787,Zhang Anda,Kacper Filipiak,7,1268,991,0.826482,0.666523,174,80,1200,...,270,82,39,169,67,4,0,0.0,1.000000,1046
2105,Craig Steadman,Fergal O'Brien,9,1330,1345,0.476942,0.490626,324,187,2127,...,356,214,117,759,395,5,3,0.0,0.625000,997

In [8]:
#Create a new dataframe df to store the modified data
df = data.loc[modify_index]

In [9]:
data.columns

Index(['player1', 'player2', 'best_of', 'player1_elo', 'player2_elo',
       'elo_match_win_rate', 'elo_frame_win_rate', 'p1_matches_played',
       'p1_matches_won', 'p1_frames_played', 'p1_frames_won',
       'p2_matches_played', 'p2_matches_won', 'p2_frames_played',
       'p2_frames_won', 'p1_frames_played_1_year', 'p1_frames_won_1_year',
       'p1_frames_played_3_years', 'p1_frames_won_3_years',
       'p2_frames_played_1_year', 'p2_frames_won_1_year',
       'p2_frames_played_3_years', 'p2_frames_won_3_years', 'score1', 'score2',
       'match_result', 'win_percentage', 'tournament_id'],
      dtype='object')

In [10]:
#Exchange the stats of player1 and player2
df['player1'], df['player2'] = df['player2'], df['player1']
df['player1_elo'], df['player2_elo'] = df['player2_elo'], df['player1_elo']
df['elo_match_win_rate'], df['elo_frame_win_rate'] = 1-df['elo_match_win_rate'], 1-df['elo_frame_win_rate']
df['p1_matches_played'], df['p1_matches_won'], df['p2_matches_played'], df['p2_matches_won'] = df['p2_matches_played'], df['p2_matches_won'], df['p1_matches_played'], df['p1_matches_won']
df['p1_frames_played'], df['p1_frames_won'], df['p2_frames_played'], df['p2_frames_won'] = df['p2_frames_played'], df['p2_frames_won'], df['p1_frames_played'], df['p1_frames_won']
df['p1_frames_played_1_year'], df['p1_frames_won_1_year'], df['p2_frames_played_1_year'], df['p2_frames_won_1_year'] = df['p2_frames_played_1_year'], df['p2_frames_won_1_year'], df['p1_frames_played_1_year'], df['p1_frames_won_1_year']
df['p1_frames_played_3_years'], df['p1_frames_won_3_years'], df['p2_frames_played_3_years'], df['p2_frames_won_3_years'] = df['p2_frames_played_3_years'], df['p2_frames_won_3_years'], df['p1_frames_played_3_years'], df['p1_frames_won_3_years']
df['score1'], df['score2'] = df['score2'], df['score1']
df['match_result'] = 1
df['win_percentage'] = 1 - df['win_percentage']

In [11]:
data.loc[modify_index] = df

In [12]:
data.head()

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
0,Mark Allen,Ricky Walden,7,1580,1418,0.709992,0.599888,501,313,3345,...,596,45,25,1032,557,0,4,1.0,0.000000,1063
1,Stephen Maguire,Judd Trump,7,1563,1551,0.516401,0.507499,663,444,4995,...,739,122,79,1344,782,1,4,1.0,0.200000,1063
2,Mark Selby,Steve Davis,7,1592,1246,0.878716,0.703704,736,495,5330,...,875,8,2,581,286,4,1,0.0,0.800000,1063
3,Neil Robertson,Ali Carter,7,1546,1544,0.502734,0.501250,621,402,4581,...,815,11,5,876,499,4,0,0.0,1.000000,1063
4,Stuart Bingham,Ronnie O'Sullivan,7,1488,1663,0.275106,0.392337,744,462,5592,...,680,71,46,674,431,2,4,1.0,0.333333,1063

In [13]:
data.loc[modify_index].head(5)

,player1,player2,best_of,player1_elo,player2_elo,elo_match_win_rate,elo_frame_win_rate,p1_matches_played,p1_matches_won,p1_frames_played,...,p1_frames_won_3_years,p2_frames_played_1_year,p2_frames_won_1_year,p2_frames_played_3_years,p2_frames_won_3_years,score1,score2,match_result,win_percentage,tournament_id
1547,Anthony Massey,Fang Xiongman,7,787,1046,0.189355,0.343553,55,7,344,...,0,22,11,82,39,0,4,1.0,0.000000,1047
49,Peter Lines,Mitchell Mann,11,1296,1158,0.720336,0.585405,637,354,4719,...,284,27,11,239,119,5,6,1.0,0.454545,1058
4616,Vinnie Calabrese,Ben Woollaston,7,1070,1338,0.181321,0.338497,97,39,617,...,132,153,81,794,428,0,4,1.0,0.000000,1110
1787,Kacper Filipiak,Zhang Anda,7,991,1268,0.173518,0.333477,43,11,230,...,67,69,33,569,270,0,4,1.0,0.000000,1046
2105,Fergal O'Brien,Craig Steadman,9,1345,1330,0.523058,0.509374,708,406,5537,...,395,268,152,702,356,3,5,1.0,0.375000,997

In [ ]:
data.to_csv('match_data_785_835_tourns_modified.csv', index=False)